### PR TITLE
New cross-platform, certificate-free, JS/CSS-able dotjs

### PR DESCRIPTION
**Pull request by luciopaiva**
Since this repo is not being maintained anymore, I don't expect this PR to be accepted any time soon. I just want to draw people's attention to my new implementation of defunkt's dotjs.

This new dotjs is cross-platform (well, it runs on all platforms supported by Node.js) and it's easier to install, since it doesn't require you to deal with any certificates.

Here's the link, in case you're interested: https://github.com/luciopaiva/witchcraft

**Update**: added the ability to include custom scripts via an `@include` directive.
**Update 2**: it now also handles CSS scripts as well

Witchcraft

### CODE REVIEW

**Comment by luciopaiva** [comment]
Added the ability to include custom scripts via an `@include` directive.

**Comment by defunkt** [comment]
Thanks, I actually added a note to the top of the README linking to Witchcraft. It looks really good - cheers!

**Comment by ghost** [comment]
Awesome, @defunkt. Thanks for the generous link and for dotjs itself.
Cheers!

**Comment by ghost** [comment]
For those interested, I recently dropped the dependency on Node.js following a suggestion from a user that didn't want to install Node.js just for that. My extension now uses a Chrome app that does the heavy lifting of fetching files from disk. I wanted to implement this mechanism inside Witchcraft itself, but then I'd need to make it a Chrome *app* instead of a Chrome *extension*. The problem is that new Chrome apps are no longer being accepted by the Chrome store; they are deprecating apps (although extensions are still being supported).

**Review by jakch78 — COMMENTED** [review]
Good

**Pull request closed without merging**
